packagebuilder/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from buildpackage import views
admin.autodiscover()



urlpatterns = patterns('',
    url(r'^$', 'buildpackage.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^oauth_response/$', 'buildpackage.views.oauth_response'),
    url(r'^select_components/(?P<package_id>[0-9A-Za-z_\-]+)/$', 'buildpackage.views.select_components'),
    url(r'^package/(?P<package_id>[0-9A-Za-z_\-]+)/$', 'buildpackage.views.package'),
    url(r'^logout/$', 'buildpackage.views.logout'),
    url(r'^job_status/(?P<package_id>[0-9A-Za-z_\-]+)/$', 'buildpackage.views.job_status'),
    url(r'^loading/(?P<package_id>[0-9A-Za-z_\-]+)/$', 'buildpackage.views.loading'),
    url(r'^auth_details/$', 'buildpackage.views.auth_details'),

    url(r'^api/package/$', 'buildpackage.views.api_create_job'),
    url(r'^api/package/status/(?P<package_id>[0-9A-Za-z_\-]+)/$', 'buildpackage.views.job_status'),
    url(r'^api/package/(?P<package_id>[-\w]+)$', 'buildpackage.views.get_package'),
)

buildpackage/forms.py
from django import forms
from django.forms import ModelForm
from buildpackage.models import Package

class LoginForm(forms.Form):

	environment = forms.CharField(required=False);
	access_token = forms.CharField(required=False)
	instance_url = forms.CharField(required=False)
	org_id = forms.CharField(required=False)

	# Options for including packages or not
	PACKAGE_CHOICES = (
		('all','All Components'),
		('unmanaged','Exclude Managed'),
		('none','No Packaged Components'),
	)

	package_option = forms.ChoiceField(choices=PACKAGE_CHOICES, required=False)

class ComponentSelectForm(forms.Form):
	component_option = forms.CharField(required=False)

packagebuilder/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Salesforce.com package.xml Builder</title>
        <meta name="keywords" content="salesforce, salesforce.com, force.com, package builder, packagebuilder, metadata, api, metadata api, package.xml, xml, destructivechanges.xml, descructivechanges, ide, force.com ide, eclipse, ant, force.com migration" /> 
        <meta name="description" content="Easily create a package.xml file based on your Salesforce org components." />
        <meta name="author" content="Ben Edwards (ben@edwards.nz)" />
        <meta charset="UTF-8" />

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/styles.css" />
        <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"/>
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/jquery.tree.css"/>
        <!--
        <link rel="shortcut icon" href="{{ STATIC_URL }}images/favicon.ico" type="image/vnd.microsoft.icon" />
        -->
        
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.tree.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/main.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-18288189-19', 'auto');
          ga('send', 'pageview');

        </script>
        {% block scripts %}{% endblock %}
    </head> 
 
    <body>

        {% if request.GET.noheader != '1' %}
            <!-- Static navbar -->
            <nav class="navbar navbar-default">

                <div class="container-fluid">

                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <div id="navbar" class="navbar-collapse collapse">

                        <ul class="nav navbar-nav navbar-left">
                            <li>
                                <a href="/" style="padding:5px;">
                                    <img src="/static/images/logo-small.png" alt="Package Builder" border="0" />
                                </a>
                            </li>
                            <li>
                                <button class="btn btn-default" data-toggle="modal" data-target="#apiModal" style="margin-left:20px;margin-top:8px;">
                                    <i class="fa fa-cogs" aria-hidden="true"></i>
                                    API
                                </button>
                            </li>
                            <li>
                                <a href="https://cloudtoolkit.co" target="_blank">Salesforce Toolkit</a>
                            </li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="https://github.com/benedwards44/packagebuilder" target="_blank">Source Code</a>
                            </li>
                            <li>
                                <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="/static/images/i-icon.png" data-toggle="modal" data-target="#infoModal" />
                                </a>
                            </li>
                        </ul>

                    </div><!--/.nav-collapse -->

                </div><!--/.container-fluid -->

            </nav>

            <div class="clear"></div>

            <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
                <div class="modal-dialog small_dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">
                                <span aria-hidden="true">&times;</span>
                                <span class="sr-only">Close</span>
                            </button>
                            <h3 class="modal-title" id="apiModalLabel">
                                Package Builder
                            </h3>
                        </div>
                        <div class="modal-body">
                            <p>
                                For any errors or issues, please feel free to contact me on twitter <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a> or via email <a href="mailto:ben@edwards.nz">ben@edwards.nz</a>.
                            </p>
                            <p>
                                I am constantly trying to update and improve this application, as well as other apps I'm working on. Feel free to contact me if you'd like to contribute or have any ideas. All my applications are open sourced on GitHub at <a href="http://github.com/benedwards44" target="_blank">http://github.com/benedwards44</a>.
                            </p>
                            <p>
                                If you haven't already, check out my other apps at the Salesforce Toolkit Page:<br/>
                                <a href="https://cloudtoolkit.co" target="_blank">https://cloudtoolkit.co</a>
                            </p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="apiModal" tabindex="-1" role="dialog" aria-labelledby="apiModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">
                                <span aria-hidden="true">&times;</span>
                                <span class="sr-only">Close</span>
                            </button>
                            <h3 class="modal-title" id="apiModalLabel">
                                API Details
                            </h3>
                        </div>
                        <div class="modal-body">
                            <h4>Step 1 - Start Job</h4>
                            Send a POST request to start your job. <br/>
                            <strong>Endpoint:</strong> <pre>http://127.0.0.1:8000/api/package/</pre>
                            <strong>Payload</strong>:
<pre>{
    "accessToken": "VALID_SALESFORCE_ACCESS_TOKEN",
    "instanceUrl": "SALESFORCE_ORG_URL",
    "componentOption": "all" // Should be "all", "unmanaged" or "none"
}</pre>

                            You will then receive an ID for the job. You use this ID to check the status of your job, and ultimately retrieve the results.
<pre>{
    "id": "6210f461-0a4b-437d-be39-f885d6f3e543",
    "success": true
}</pre>

                            <br/>
                            <h4>Step 2 - Check Progress</h4>
                            The API runs asynchronously, as jobs can take some time to run depending on the size of your code base. You need to check the status of the job, and when complete you can get your results. Send a GET request to: <br/>
                            <strong>Endpoint:</strong> <pre>http://127.0.0.1:8000/api/package/status/PACKAGE_ID (eg. http://127.0.0.1:8000/api/package/status/6210f461-0a4b-437d-be39-f885d6f3e543)</pre>
                            <strong>Response:</strong>
<pre>{
    "status": "Processing",
    "done": false,
    "success": false,
    "error": null
}</pre>
                            The done and success variables will help you determine when your job is complete, and if it's successful.

                            <br/>
                            <h4>Step 3 - Get Results</h4>
                            And finally, you can get your results. Send a GET request to: <br/>
                            <strong>Endpoint:</strong> <pre>http://127.0.0.1:8000/api/package/PACKAGE_ID (eg. http://127.0.0.1:8000/api/package/6210f461-0a4b-437d-be39-f885d6f3e543)</pre>
                            <strong>Response:</strong>
<pre>[
    {
        "id": "6210f461-0a4b-437,d-be39-f885d6f3e543",
        "status" "Finished" 
        "componentOption": "all" // The selected option for the package
        "xml": "<Package xmlns="http://soap.sforce.com/2006/04/metadata">....</Package>" // The full package XML
    },
]</pre>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

        {% endif %}

        <div class="{% if request.GET.noheader == '1' %}col-md-12{% else %}col-md-6 col-md-offset-3{% endif %}">
            {% block content %}{% endblock %}
        </div>

    </body>

</html>

packagebuilder/templates/index.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce package.xml Builder</h1>

	<p>
		This tool uses the Salesforce Metadata API to build a package.xml file based on components in your Salesforce org. Handy for building a package.xml file for use with ANT Force.com Migration or other IDE tools, or building a destructiveChanges.xml file.
	</p>
	<p>
		Faster than having to download all the actual metadata in order to build your package.xml file.
	</p>
	<div class="alert alert-info alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<strong>Note:</strong>
		This application uses multiple API calls to your Salesforce Org to retrieve metadata and execute the logic it needs to run. Each Salesforce Org has a 24 hour limit of API calls it can make, and may break other integrations if you exceed this limit.
	</div>
				
	<table id="login_table">

		<form action="." method="POST" onsubmit="hideTable();" oncomplete="showTable();" id="loginForm"> {% csrf_token %}

			<table class="login_table">

				<tr>
					<td colspan="2" style="color:#ff6600;font-weight:bold;">
						<h2>Select Options</h2>
					</td>
				</tr>

				{% if login_form.errors or login_form.non_field_errors %}
					<tr>
						<td colspan="2" style="color:#ff6600;font-weight:bold;">
							{{ login_form.errors}} <br/>
							{{ login_form.non_field_errors }}
						</td>
					</tr>
				{% endif %}

				{% if messages %}
					<tr>
						<td colspan="2" style="color:#ff6600;font-weight:bold;">
						    {% for message in messages %}
						    	{{ message }}<br/>
						    {% endfor %}
						    <br/>
						</td>
					</tr>
				{% endif %}

				<tr>
					<td width="200">
						<label for="id_environment">Environment</label>
					</td>
					<td>
						<select id="id_environment" name="environment" class="form-control">
							<option value="Production">Production</option>
							<option value="Sandbox">Sandbox</option>
						</select>
					</td>
				</tr>

				<tr>
					<td colspan="2">&nbsp;</td>
				</tr>

				<tr>
					<td colspan="2" style="text-align:center;height:50px;">
						<input type="submit" value="Login to Salesforce with OAuth" />
					</td>
				</tr>

			</table>

			<div class="loading">
				<div style="float:left;">
					<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
				</div>
				<div style="float:left;margin-left:20px;">
					<h1 style="font-size:1.5em;margin-top:20px;">Accessing Salesforce...</h1>
					<p>Logging in with OAuth 2.0</p>
				</div>
			</div>

		</form>

	</table>

{% endblock %}

packagebuilder/templates/loading.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce package.xml Builder</h1>

	<p>
		This tool uses the Salesforce Metadata API to build a package.xml file based on components in your Salesforce org. Handy for building a package.xml file for use with ANT Force.com Migration or other IDE tools, or building a destructiveChanges.xml file.
	</p>
	<p>
		Faster than having to download all the actual metadata in order to build your package.xml file.
	</p>
				
	<div class="loading-components">

		<div style="float:left;">
			<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
		</div>

		<div style="float:left;margin-left:20px;">
			<h1 style="font-size:1.5em;margin-top:20px;">Querying components...</h1>
			<p>This can take a few minutes.</p>
		</div>

	</div>

	<div role="alert" class="error alert alert-danger" style="display:none;">
		<p>
			There was an error processing your request: <i class="error_message"></i>
			<br/><br/>
			Please <a href="/">return</a> to the home page and try again.
		</p>
	</div>

	<script>
		var refreshId = window.setInterval(function () 
 		{
       		$.ajax({
			    url: '/job_status/{{ package.random_id }}',
			    type: 'get', //this is the default though, you don't actually need to always mention it
			    success: function(resp) 
			    {
			        if (resp.status == 'Finished')
			        {
			        	window.location = '/package/{{ package.random_id }}/';
			        } 
			        else if (resp.status == 'Error')
			        {
			        	$('.loading-components').hide();
			        	$('.error').show();
			        	$('.error_message').text(resp.error);
			        	clearInterval(refreshId);
			        }
			        // Else job is still running, this will re-run shortly.
			    },
			    failure: function(resp) 
			    { 
			        $('.loading-components').hide();
		        	$('.error').show();
		        	$('.error_message').text(resp);
		        	clearInterval(refreshId);
			    }
			});
    	}, 3000);
	</script>

{% endblock %}

packagebuilder/templates/logout.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce package.xml Builder</h1>
	<p>
		Successfully logged out of Salesforce and Package Builder. You will be directed back to the home page where you will need to re-login using the OAuth link.
	</p>

	<iframe src="https://{{ instance }}.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>

	<script>
		setTimeout(function () {
       		window.location.href = "/";
    	}, 4000);
	</script>
{% endblock %}

packagebuilder/templates/oauth_response.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}

	<h1>Salesforce package.xml Builder</h1>
	<p>
		This tool uses the Salesforce Metadata API to build a package.xml file based on components in your Salesforce org. Handy for building a package.xml file for use with ANT Force.com Migration or other IDE tools, or building a destructiveChanges.xml file.
	</p>
	<p>
		Faster than having to download all the actual metadata in order to build your package.xml file.
	</p>
				
	<table id="login_table">

		<form action="." method="POST" id="loginForm"> {% csrf_token %}

			<table class="login_table">

				{% if messages %}

					<tr>
						<td colspan="2">
							<div role="alert" class="alert alert-danger">
							    {% for message in messages %}
							    	{{ message }}<br/>
							    {% endfor %}
						    </div>
						</td>
					</tr>
					
				{% endif %}

				{% if not error %}

					<h2>Logged in as:</h2>

						<tr>
							<td width="150">
								<strong>Username:</strong>
							</td>
							<td>
								{{ username }}
							</td>
						</tr>

						<tr>
							<td width="150">
								<strong>Organisation:</strong>
							</td>
							<td>
								{{ org_name }}
							</td>
						</tr>

						<tr>
							<td colspan="2"><br/></td>
						</tr>

						<tr>
							<td width="150">
								<strong>Component Option:</strong>
							</td>
							<td>
								{% render_field login_form.package_option class="form-control" %}
							</td>
						</tr>

						<tr>
							<td colspan="2"><br/></td>
						</tr>

					<tr>
						<td colspan="2" style="text-align:center;height:50px;">
							<input type="submit" name="logout" value="Logout" onclick="showLogout();" oncomplete="hideLogout();" />
							<input type="submit" name="get_components" value="Get Components" onclick="hideTable();" oncomplete="showTable();" />
						</td>
					</tr>

				{% else %}

				<tr>
					<td colspan="2">
						<div role="alert" class="alert alert-danger">
							{{ error_message }}
							<br/><br/>
							Please go <a href="/">back</a> and try again.
						</div>
					</td>
				</tr>

				{% endif %}

			</table>

			<div class="loading">

				<div style="float:left;">
					<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
				</div>

				<div style="float:left;margin-left:20px;">
					<h1 style="font-size:1.5em;margin-top:20px;">Querying components...</h1>
					<p>This can take a few minutes.</p>
				</div>
				
			</div>

			<div class="logging_out">
				<div style="float:left;">
					<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
				</div>
				<div style="float:left;margin-left:20px;">
					<h1 style="font-size:1.5em;margin-top:20px;">Logging out...</h1>
					<p>Revoking OAuth token.</p>
				</div>
			</div>

			<div style="display:none;">
				{{ login_form.environment }}
				{{ login_form.access_token }}
				{{ login_form.instance_url }}
				{{ login_form.org_id }}
			</div>

		</form>

	</table>

{% endblock %}

packagebuilder/templates/package.html
<html>

	<head>
		<title>Package.xml</title>
	</head>
	
	<body>
		<pre>{{ package_xml }}</pre>
	</body>

</html>

packagebuilder/templates/select_components.html
{% extends 'base.html' %}

{% block content %}

	<h1>Select components or continue with all</h1>

	<form action="." method="POST" id="select_components" onsubmit="hideTable();" oncomplete="showTable();"> {% csrf_token %}

		<div class="loading-component-selector">

			<div style="float:left;">
				<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
			</div>

			<div style="float:left;margin-left:20px;">
				<h1 style="font-size:1.5em;margin-top:20px;">Building component list...</h1>
				<p></p>
			</div>

		</div>

		<table class="select-component-options" style="display:none;">

			<tr>
				<td colspan="2" ><input type="submit" value="Build Package >>" /></label>
			</tr>

			<tr>
				<td colspan="2" style="text-align:center;">&nbsp;</label>
			</tr>

			<tr>
				<td><input id="selectAll" type="radio" name="select" value="all" /></td>
				<td><label for="selectAll">Continue With All Components</label>
			</tr>

			<tr>
				<td><input id="selectPartial" type="radio" name="select" value="partial" /></td>
				<td><label for="selectPartial">Select Partial Components</label>
			</tr>

		</table>

		<div id="selection_tree" style="display:none;">
			<button class="treeButton" type="button" onclick="$('#selection_tree').find(':checkbox').prop('checked', true);" >Check All</button>
			<button class="treeButton" type="button" onclick="$('#selection_tree').find(':checkbox').prop('checked', false);" >Deselect All</button>
			<button class="treeButton" type="button" onclick="$('#selection_tree').tree('expandAll');" >Expand All</button>
			<button class="treeButton" type="button" onclick="$('#selection_tree').tree('collapseAll');" >Collapse All</button>
			<ul>
				{% for component_type in package.sorted_component_types %}

                	<li class="collapsed">
                		<input class="component_type_display" name="{{ forloop.counter0 }}" type="checkbox">
                		<span>{{ component_type.name }}</span>

                	{% for component in component_type.sorted_components %}
                    <ul>
                        <li>
                        	<input class="component_display" type="checkbox" name="{{ component.id }}">
                        	<span>{{ component.name }}</span>
                    </ul>
                    {% endfor %}

                {% endfor %}
            	
            </ul>
        </div>
                    
        <input type="hidden" id="id_component_option" name="component_option" />

        <div style="display:none;">

		    {{ component_type_formset.management_form }}
		    {% for component_type_form in component_type_formset %}
		        {{ component_type_form.as_p }}
		    {% endfor %}

		    {{ component_formset.management_form }}
		    {% for component_form in component_formset %}
		    	{{ component_form.as_p }}
		    {% endfor %}

		</div>
	    
	</form>

	<div class="loading">
		<div style="float:left;">
			<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
		</div>
		<div style="float:left;margin-left:20px;">
			<h1 style="font-size:1.5em;margin-top:20px;">Building xml...</h1>
			<p>Almost there.</p>
		</div>
	</div>


{% endblock %}